export const Routes = {
  Home: '/',
  About: '/about',
  News: '/news',
  NewsCurrent: (id: string) => `/news/${id}`,
  Docs: '/docs',
  Donations: '/donations',
  Church: '/church',
  Leaders: '/leaders',
  Leader: (slug: string) => `/leaders/${slug}`,
  Login: '/login',
  Dashboard: '/dashboard',
  DashboardNews: '/dashboard/news',
  DashboardNewsCreate: '/dashboard/news/new',
  DashboardNewsCurrent: (id: string) => `/dashboard/news/${id}`,
  DashboardDocs: '/dashboard/docs',
  DashboardDocsCreate: '/dashboard/docs/new',
  DashboardDocsCurrent: (id: string) => `/dashboard/docs/${id}`,
  DashboardLeaders: '/dashboard/leaders',
  DashboardLeadersCreate: '/dashboard/leaders/new',
  DashboardLeadersCurrent: (slug: string) => `/dashboard/leaders/${slug}`,
};
